local KeyPressed = require("boom.events.KeyPressed")
local MousePressed = require("boom.events.MousePressed")
local KeyReleased = require("boom.events.KeyReleased")
local MouseReleased = require("boom.events.MouseReleased")
local NetKeyPressed = require("boom.events.NetKeyPressed")
local NetKeyReleased = require("boom.events.NetKeyReleased")
local InputPressed = require("boom.events.InputPressed")
local InputReleased = require("boom.events.InputReleased")
local SnapshotReceived = require("boom.events.SnapshotReceived")
local LoginRes = require("boom.events.LoginRes")
local CreateRoomRes = require("boom.events.CreateRoomRes")
local EnterRoomBroadcast = require("boom.events.EnterRoomBroadcast")
local EnterRoomRes = require("boom.events.EnterRoomRes")
local GameBeginBroadcast = require("boom.events.GameBeginBroadcast")
local GameCancelReadyBroadcast = require("boom.events.GameCancelReadyBroadcast")
local GameReadyBroadcast = require("boom.events.GameReadyBroadcast")
local GetRoomListRes = require("boom.events.GetRoomListRes")
local QuitRoomBroadcast = require("boom.events.QuitRoomBroadcast")
local BeginContact = require("boom.events.BeginContact")
local EndContact = require("boom.events.EndContact")
local PreSolve = require("boom.events.PreSolve")
local PostSolve = require("boom.events.PostSolve")
local Damage = require("boom.events.Damage")
local EntityDestroy = require("boom.events.EntityDestroy")

local events = {
    KeyPressed = KeyPressed,
    MousePressed = MousePressed,
    KeyReleased = KeyReleased,
    MouseReleased = MouseReleased,
    NetKeyPressed = NetKeyPressed,
    NetKeyReleased = NetKeyReleased,
    InputPressed = InputPressed,
    InputReleased = InputReleased,
    SnapshotReceived = SnapshotReceived,
    LoginRes = LoginRes,
    CreateRoomRes = CreateRoomRes,
    EnterRoomBroadcast = EnterRoomBroadcast,
    EnterRoomRes = EnterRoomRes,
    GameBeginBroadcast = LoginRes,
    GameCancelReadyBroadcast = GameCancelReadyBroadcast,
    GameReadyBroadcast = GameReadyBroadcast,
    GetRoomListRes = GetRoomListRes,
    QuitRoomBroadcast = QuitRoomBroadcast,
    BeginContact = BeginContact,
    EndContact = EndContact,
    PreSolve = PreSolve,
    PostSolve = PostSolve,
    Damage = Damage,
    EntityDestroy = EntityDestroy,
}
return events
