local KeyPressed = require("boom.events.KeyPressed")
local MousePressed = require("boom.events.MousePressed")
local KeyReleased = require("boom.events.KeyReleased")
local MouseReleased = require("boom.events.MouseReleased")
local NetKeyPressed = require("boom.events.NetKeyPressed")
local NetKeyReleased = require("boom.events.NetKeyReleased")
local InputPressed = require("boom.events.InputPressed")
local InputReleased = require("boom.events.InputReleased")
local CreateRoomInputPressed = require("boom.events.CreateRoomInputPressed")
local RoomListInputPressed = require("boom.events.RoomListInputPressed")
local RoomListInputReleased = require("boom.events.RoomListInputReleased")
local RoomInputPressed = require("boom.events.RoomInputPressed")
local RoomInputReleased = require("boom.events.RoomInputReleased")
local SnapshotReceived = require("boom.events.SnapshotReceived")
local LoginRes = require("boom.events.LoginRes")
local CreateRoomRes = require("boom.events.CreateRoomRes")
local EnterRoomBroadcast = require("boom.events.EnterRoomBroadcast")
local EnterRoomRes = require("boom.events.EnterRoomRes")
local GameBeginBroadcast = require("boom.events.GameBeginBroadcast")
local GameCancelReadyBroadcast = require("boom.events.GameCancelReadyBroadcast")
local GameReadyBroadcast = require("boom.events.GameReadyBroadcast")
local GetRoomListRes = require("boom.events.GetRoomListRes")
local QuitRoomBroadcast = require("boom.events.QuitRoomBroadcast")

local events = {
    KeyPressed = KeyPressed,
    MousePressed = MousePressed,
    KeyReleased = KeyReleased,
    MouseReleased = MouseReleased,
    NetKeyPressed = NetKeyPressed,
    NetKeyReleased = NetKeyReleased,
    InputPressed = InputPressed,
    InputReleased = InputReleased,
    CreateRoomInputPressed = CreateRoomInputPressed,
    SnapshotReceived = SnapshotReceived,
    LoginRes = LoginRes,
    CreateRoomRes = CreateRoomRes,
    RoomListInputPressed = RoomListInputPressed,
    RoomListInputReleased = RoomListInputReleased,
    RoomInputPressed = RoomInputPressed,
    RoomInputReleased = RoomInputReleased,
    EnterRoomBroadcast = EnterRoomBroadcast,
    EnterRoomRes = EnterRoomRes,
    GameBeginBroadcast = LoginRes,
    GameCancelReadyBroadcast = GameCancelReadyBroadcast,
    GameReadyBroadcast = GameReadyBroadcast,
    GetRoomListRes = GetRoomListRes,
    QuitRoomBroadcast = QuitRoomBroadcast,
}
return events
